import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, type Dirent } from "node:fs";
import { dirname, join } from "node:path";
import type {
  HealthRiskProfile,
  HealthRiskProfileSource,
  PluginConfig,
  TangConfigFileMetadata,
} from "./types.js";

export const TANG_CONFIG_FILE_NAME = ".oh-my-tang.json";
export const TANG_CONFIG_FILE_MEANING =
  "Shows where Tang reads editable runtime settings and whether the config file had to be generated or recovered.";

const SKIPPED_DIRECTORIES = new Set([".git", "node_modules", ".tang-dynasty", "dist"]);

export const TANG_DEFAULT_PLUGIN_CONFIG: Pick<
  PluginConfig,
  "maxConcurrentMinistries" | "maxReviewRounds" | "tokenBudgetLimit" | "healthRiskProfile" | "enableParallelExecution" | "verbose"
> = {
  maxConcurrentMinistries: 3,
  maxReviewRounds: 3,
  tokenBudgetLimit: 100_000,
  healthRiskProfile: "balanced",
  enableParallelExecution: true,
  verbose: false,
};

type TangEditableConfig = typeof TANG_DEFAULT_PLUGIN_CONFIG;

type TangConfigField = keyof TangEditableConfig;

type ResolvedTangConfig = {
  config: Partial<PluginConfig>;
  configFile: TangConfigFileMetadata;
  warnings: string[];
};

function isHealthRiskProfile(value: unknown): value is HealthRiskProfile {
  return value === "balanced" || value === "strict" || value === "relaxed";
}

function findOpencodeConfig(worktree: string): string | undefined {
  const queue = [worktree];

  while (queue.length > 0) {
    const directory = queue.shift();
    if (!directory) {
      continue;
    }

    const candidate = join(directory, "opencode.json");
    if (existsSync(candidate)) {
      return candidate;
    }

    let entries: Dirent[];
    try {
      entries = readdirSync(directory, { withFileTypes: true });
    } catch {
      continue;
    }

    for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
      if (!entry.isDirectory() || SKIPPED_DIRECTORIES.has(entry.name)) {
        continue;
      }

      queue.push(join(directory, entry.name));
    }
  }

  return undefined;
}

function createConfigMetadata(
  path: string,
  source: TangConfigFileMetadata["source"],
  autoGenerated: boolean,
  foundOpencodeConfig: boolean,
): TangConfigFileMetadata {
  return {
    path,
    source,
    autoGenerated,
    foundOpencodeConfig,
    meaning: TANG_CONFIG_FILE_MEANING,
  };
}

function validateConfigField(key: TangConfigField, value: unknown): value is TangEditableConfig[TangConfigField] {
  switch (key) {
    case "maxConcurrentMinistries":
    case "maxReviewRounds":
    case "tokenBudgetLimit":
      return Number.isInteger(value) && Number(value) > 0;
    case "enableParallelExecution":
    case "verbose":
      return typeof value === "boolean";
    case "healthRiskProfile":
      return isHealthRiskProfile(value);
  }
}

function validateConfigObject(parsed: unknown): Pick<PluginConfig, keyof TangEditableConfig> & {
  healthRiskProfileSource: HealthRiskProfileSource;
} {
  const resolved = {
    ...TANG_DEFAULT_PLUGIN_CONFIG,
    healthRiskProfileSource: "default" as HealthRiskProfileSource,
  };

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    return resolved;
  }

  for (const [key, value] of Object.entries(parsed) as Array<[TangConfigField, unknown]>) {
    if (!(key in TANG_DEFAULT_PLUGIN_CONFIG)) {
      continue;
    }

    if (!validateConfigField(key, value)) {
      continue;
    }

    switch (key) {
      case "maxConcurrentMinistries":
        resolved.maxConcurrentMinistries = value as TangEditableConfig["maxConcurrentMinistries"];
        break;
      case "maxReviewRounds":
        resolved.maxReviewRounds = value as TangEditableConfig["maxReviewRounds"];
        break;
      case "tokenBudgetLimit":
        resolved.tokenBudgetLimit = value as TangEditableConfig["tokenBudgetLimit"];
        break;
      case "enableParallelExecution":
        resolved.enableParallelExecution = value as TangEditableConfig["enableParallelExecution"];
        break;
      case "verbose":
        resolved.verbose = value as TangEditableConfig["verbose"];
        break;
      case "healthRiskProfile":
        resolved.healthRiskProfile = value as TangEditableConfig["healthRiskProfile"];
        resolved.healthRiskProfileSource = "config";
        break;
    }
  }

  return resolved;
}

export function resolveTangConfig(worktree: string): ResolvedTangConfig {
  const warnings: string[] = [];
  const opencodeConfigPath = findOpencodeConfig(worktree);
  const configDirectory = opencodeConfigPath ? dirname(opencodeConfigPath) : worktree;
  const tangConfigPath = join(configDirectory, TANG_CONFIG_FILE_NAME);
  const foundOpencodeConfig = Boolean(opencodeConfigPath);

  if (!foundOpencodeConfig) {
    warnings.push("Could not find opencode.json under the current worktree; generated .oh-my-tang.json in the worktree root.");
  }

  if (!existsSync(tangConfigPath)) {
    try {
      mkdirSync(configDirectory, { recursive: true });
      writeFileSync(tangConfigPath, JSON.stringify(TANG_DEFAULT_PLUGIN_CONFIG, null, 2));
      return {
        config: {
          ...TANG_DEFAULT_PLUGIN_CONFIG,
          healthRiskProfileSource: "default",
        },
        configFile: createConfigMetadata(tangConfigPath, "auto-generated", true, foundOpencodeConfig),
        warnings,
      };
    } catch (error) {
      warnings.push(`Failed to write ${TANG_CONFIG_FILE_NAME}: ${error instanceof Error ? error.message : String(error)}`);
      return {
        config: {
          ...TANG_DEFAULT_PLUGIN_CONFIG,
          healthRiskProfileSource: "default",
        },
        configFile: createConfigMetadata(tangConfigPath, "write-failed-fallback", false, foundOpencodeConfig),
        warnings,
      };
    }
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(tangConfigPath, "utf8"));
  } catch (error) {
    warnings.push(`Failed to parse ${TANG_CONFIG_FILE_NAME}; using built-in defaults. ${error instanceof Error ? error.message : String(error)}`);
    return {
      config: {
        ...TANG_DEFAULT_PLUGIN_CONFIG,
        healthRiskProfileSource: "default",
      },
      configFile: createConfigMetadata(tangConfigPath, "invalid-file-fallback", false, foundOpencodeConfig),
      warnings,
    };
  }

  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
    for (const [key, value] of Object.entries(parsed) as Array<[TangConfigField, unknown]>) {
      if (!(key in TANG_DEFAULT_PLUGIN_CONFIG)) {
        continue;
      }

      if (!validateConfigField(key, value)) {
        warnings.push(`Ignoring invalid "${TANG_CONFIG_FILE_NAME}" value for "${key}".`);
      }
    }
  }

  return {
    config: validateConfigObject(parsed),
    configFile: createConfigMetadata(tangConfigPath, "file", false, foundOpencodeConfig),
    warnings,
  };
}
